### ISSUE TITLE
Any plans to support Async Specifications?

### ISSUE THREAD

**Issue by Benji-Yarmand** [jnicolau/NSpecifications#10]
Hi João Oliveira
Thanks for the great job!
Am I doing it wrong if I need to make a DB/API call in one of my Specs.
I know that I might be able to make those calls before using the Spec, however it would be much cleaner if I can keep that knowledge to the Speck as well.
Thanks.

**Comment by MiroslavMikus** [comment]
Hi @Benji-Yarmand,
I'm not sure what is the problem with your async DB/API call. You can use NSpecification with any sync and async api...

Example with EntityFramework:
```csharp
public async Task<Drink> GetDrinkAsync(IDbContext context)
{
    ASpec<Drink> whiskeySpec = new Spec<Drink>(d => d.Name.ToLower() == "whiskey");

    // WhereAsync accepts Expression<Func<T, bool>>
    var myWhiskey = await context.Drinks.WhereAsync(whiskeySpec);

    return myWhiskey;
}
```

You can imagine NSpecifications as Expression/Func builder library.

Have a nice day 😄

**Comment by jnicolau** [comment]
@MiroslavMikus explained it very well. Since there are no further questions I'm going to close the issue.
