### ISSUE TITLE
Add 'because' to ASpec

### ISSUE THREAD

**Issue by MiroslavMikus** [jnicolau/NSpecifications#11]
Hi, great framework :)

Would it be possible/meaningful to add 'because' parameter to the ASpec implementation?

```csharp
ASpec<Drink> whiskeySpec = new Spec<Drink>(d => d.Name.ToLower() == "whiskey", because = "I like whiskey");
```
The background story:
We are developing API and our DTO`s have a validation pipeline build-out of specifications. If one of them fails, I would like to know which one. 

For example: `I do not accept this drink, because: I like whiskey`
Thanks

**Comment by jnicolau** [comment]
Yes, you can just extend the original ASpec and Spec classes and add an
extra parameter in the constructor and a getter to return the "because"
property.

Regards,
Joao
