### ISSUE TITLE
Is(T candidate) instead of IsSatisfiedBy(T candidate)

### ISSUE THREAD

**Issue by gabayben** [jnicolau/NSpecifications#18]
https://github.com/jnicolau/NSpecifications/blob/68e56cef95f52b23a0231bd49752bb2d9997b348/Nspecifications/ASpec.cs#L203

**Comment by jnicolau** [comment]
I find it a great idea but won't change it now it because it would be a breaking change for the people that are already using this library, nevertheless I encourage you to create your own fork with that change if you want to.
