### ISSUE TITLE
Nuget. Warning!

### ISSUE THREAD

**Issue by sergeylopatyuk** [jnicolau/NSpecifications#5]
package 'NSpecifications 1.0.1' was restored using '.netframework version=v4.6.1' instead of the project target framework '.NetCoreApp,version=v2.0' This package may not be fully compatible with your project.

Please update nuget package

**Comment by jnicolau** [comment]
I've just published the Nuget package v1.1.0 for .Net Standard 1.0
https://www.nuget.org/packages/NSpecifications/1.1.0
Let me know if it works for you.

**Comment by sergeylopatyuk** [comment]
tnx, works fine!
