### ISSUE TITLE
Support OrderBy, OrderByDescending, Take, Skip

### ISSUE THREAD

**Issue by irperez** [jnicolau/NSpecifications#7]
Would it be possible to support OrderBy, OrderByDescending, Take, Skip methods?

I could do it, but I would need some guidance on how to approach it.  I suspect it would require some change since this would expand the functionality beyond the where predicate.

**Comment by jnicolau** [comment]
That's already supported by IEnumerable and IQueryable.

**Comment by jnicolau** [comment]
I did not expand the 'Where' predicate, I only made it so that you can use specifications anywhere in place of Expressions. It just happens that 'Where' method receives an Expression, and so do many other Linq extensions methods such as First, Select ...
